content:
  - name: meeting
    label: Meeting
    path: src/data/nextMeeting.json
    type: file
    fields:
      - name: date
        label: Date
        type: date
      - name: location
        label: location
        type: string
      - name: website
        label: website
        type: url
