content:
  - name: meeting
    label: Meeting
    path: src/data/nextMeeting.json
    type: file
    fields:
      - name: date
        label: Date
        type: date
      - name: church
        label: Church
        type: string
      - name: city
        label: City
        type: string
      - name: website
        label: URL
        type: string
      - name: text
        label: Text
        type: text
